### ISSUE TITLE
Not working in magento 2.2.2

### ISSUE THREAD

**Issue by magegirl** [experius/Magento-2-Module-Experius-ExtraCheckoutAddressFields#8]
I add custom attribute "etage" and i have this error Property "Etage" does not have corresponding setter in class "Magento\Quote\Api\Data\AddressExtensionInterface".

**Comment by Sarvesh-A** [comment]
@magegirl , Have you got any solution regarding setter error?

**Comment by magegirl** [comment]
Hello @Sarvesh-A no solution for now
